language: ruby
rvm:
- ruby-head
- 2.5.1
- 2.4.4
- 2.3.7
- 2.2.10
- 2.1.10
before_install: gem install bundler -v 1.16.0
env:
  global:
  - secure: l7d7xdM1tyArzZ9vqFaCdZGjk8U50WL+5Z+vAekWmN78zFgMOvnH9nHOOT5e/0f4eOHm7BeUMYUqD4W2uaTddLWRswmf8rMqNDYPGO1BZwWzAu+X+h1MYbRbOVdGtsZZ1qEeuJX6cVVOxZVt8OsIN2BQRzOI/wTCfoPHyJ4dx+nz2vcqqbsV/AyBUJ8OTZdtxDvR2NdxEZbGKdXBKvxNIXhudLz1LqImDgqyDp2msLDMk29Bau3YfFOwpRy0gp2GMgzy/kFsLqnpB/A3azsXyiTpkw3YLeZx0PYlpekPMZxiWXElvGqJVrkmOZWBMLLQwVL9NAdJm57AuNxtAEZ2Y4gog+ef/WAtlj35LcieSzqupIFrdcpOJxzuqFqe10YO8SO1lA8bzUOk3n5DBDxRf/TjVjqBdFiigMia0PsE13NXGX/GkasLcjYiwIPpYnCny7MqmtEBNn3F+fvsJ3HM2OLAWvqbB8rjQr5pFsYljiZr1JvucTpwSP+XwIoPpsjRRlZC2athUp0Iam/rtk19pYFh/xd/jdwF6taVAJ08Phs1Ay6h9uU7FMR/AwfDOHy3cMqR966qPyWo+BrbMGuAOSs0CtDYQXjvRi3pswYUY44Sc2KXSuChtxQKibQ+cfwQgDT4dnqTbIl3dzV3QNse4S0AdJYBFqc4BMOcQuYyfrM=
  - secure: yNlluUeLR8hklJnMZ3ivSuJb1tH/x4eWcvmYdasSuqwGi40KxoRxcEi+cnTo2jPSbv2f2y/2DZcX2+fCdUgnoLm1BW9jEzk81bfoGh6ha7c24C4TDAOkLkRiyqDNe/p39tjcALqPxrG6WIwZ43cGy4dZdUCwjDaxTSbrfNm4kCop2nFAY938BGSmlU75TJyIKiPwaM0TWMznb8pt2ETZFwx0+Nbu8wsExRrR617vBlbYwPz+YnrK9zqUlaPu7hXx+TS0CutDAUpE/WS7m/RXxGX54WmVQAFUlwHcZoQ2BeMmgk+yRw8wtfdxxzw3sD5FcRNrZxjkooam2dEEm0g1dRsVtoxO0dHcAlbjZmTahyWTpufr7EnEhkM0WDNjtrxBqCn0/TJW2YV9q0iZStrurgj1ynY+dkOHbEKUFITWX1w6FMvOOkl12YnuODHXkoyFwtIfCy+2ZyiA/BelKSZukKopMe/X9B/oX0iHK3e+FGbkB40ApQrLBgYMx4E2mBxFqyPqpDiCs/Smeh2W3pGBWNRPe8trs/ZFe1xEeAzXgI8icjf4qx06uM4Fu+7CjSp+mxa+uNsi35ap/ykc5M60Vqo8zNEmLBtvrmb8r32xcTQ1MjiiHWaBWMaR324FIV/Dz0STlmt32Tabzqs6tKagxyXW6Bc3QnN1Gj36qRsubPg=
